# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetRooti <- function(Cov) {
    .Call('_spatempBFA_GetRooti', PACKAGE = 'spatempBFA', Cov)
}

getRootiH <- function(Psi, Nu, TempCorInd, seasonPeriod) {
    .Call('_spatempBFA_getRootiH', PACKAGE = 'spatempBFA', Psi, Nu, TempCorInd, seasonPeriod)
}

getInvH <- function(Psi, Nu, TempCorInd, seasonPeriod) {
    .Call('_spatempBFA_getInvH', PACKAGE = 'spatempBFA', Psi, Nu, TempCorInd, seasonPeriod)
}

getH <- function(Psi, TempCorInd, TimeDist, Nu, seasonPeriod) {
    .Call('_spatempBFA_getH', PACKAGE = 'spatempBFA', Psi, TempCorInd, TimeDist, Nu, seasonPeriod)
}

SpEXP <- function(rho, SpDist) {
    .Call('_spatempBFA_SpEXP', PACKAGE = 'spatempBFA', rho, SpDist)
}

GetLogLik <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatempBFA_GetLogLik', PACKAGE = 'spatempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

GetLogLikMean <- function(DatObj_List, Para_List) {
    .Call('_spatempBFA_GetLogLikMean', PACKAGE = 'spatempBFA', DatObj_List, Para_List)
}

SamplePPD <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatempBFA_SamplePPD', PACKAGE = 'spatempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

VAR1bfaRcppFixedL <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, ParaCL_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spatempBFA_VAR1bfaRcppFixedL', PACKAGE = 'spatempBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, ParaCL_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

VAR1bfaRcppVaryingLjs <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spatempBFA_VAR1bfaRcppVaryingLjs', PACKAGE = 'spatempBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

bfaRcppFixedL <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, ParaCL_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spatempBFA_bfaRcppFixedL', PACKAGE = 'spatempBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, ParaCL_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

bfaRcppVaryingLjs <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spatempBFA_bfaRcppVaryingLjs', PACKAGE = 'spatempBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

EtaKrigging <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatempBFA_EtaKrigging', PACKAGE = 'spatempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

VAR1EtaKrigging <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatempBFA_VAR1EtaKrigging', PACKAGE = 'spatempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

LambdaKrigging <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatempBFA_LambdaKrigging', PACKAGE = 'spatempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

AlphaKriggingFixedL <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatempBFA_AlphaKriggingFixedL', PACKAGE = 'spatempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

AlphaKriggingVaryLj <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatempBFA_AlphaKriggingVaryLj', PACKAGE = 'spatempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

YKriggingTemp <- function(DatObj_List, Para_List, EtaKrig, NKeep, Verbose) {
    .Call('_spatempBFA_YKriggingTemp', PACKAGE = 'spatempBFA', DatObj_List, Para_List, EtaKrig, NKeep, Verbose)
}

VAR1YKriggingTemp <- function(DatObj_List, Para_List, EtaKrig, NKeep, Verbose) {
    .Call('_spatempBFA_VAR1YKriggingTemp', PACKAGE = 'spatempBFA', DatObj_List, Para_List, EtaKrig, NKeep, Verbose)
}

YKriggingSpat <- function(DatObj_List, Para_List, LambdaKrig, NKeep, Verbose) {
    .Call('_spatempBFA_YKriggingSpat', PACKAGE = 'spatempBFA', DatObj_List, Para_List, LambdaKrig, NKeep, Verbose)
}

UpdateLjVec <- function(U, Weights, K, M, O, LjVec) {
    .Call('_spatempBFA_UpdateLjVec', PACKAGE = 'spatempBFA', U, Weights, K, M, O, LjVec)
}

UpdateAlpha <- function(Alpha, K, M, O, LjVec) {
    .Call('_spatempBFA_UpdateAlpha', PACKAGE = 'spatempBFA', Alpha, K, M, O, LjVec)
}

GetWeightsVaryLj <- function(Alpha, K, M, O, LjVec) {
    .Call('_spatempBFA_GetWeightsVaryLj', PACKAGE = 'spatempBFA', Alpha, K, M, O, LjVec)
}

GetWeightsFixedL <- function(Alpha, K, M, L, O) {
    .Call('_spatempBFA_GetWeightsFixedL', PACKAGE = 'spatempBFA', Alpha, K, M, L, O)
}

GetLogWeightsFixedL <- function(Alpha, K, M, L, O) {
    .Call('_spatempBFA_GetLogWeightsFixedL', PACKAGE = 'spatempBFA', Alpha, K, M, L, O)
}

CholInv <- function(Cov) {
    .Call('_spatempBFA_CholInv', PACKAGE = 'spatempBFA', Cov)
}

whichJsCalc <- function(nnInd) {
    .Call('_spatempBFA_whichJsCalc', PACKAGE = 'spatempBFA', nnInd)
}

getCloseNNDmat <- function(matx) {
    .Call('_spatempBFA_getCloseNNDmat', PACKAGE = 'spatempBFA', matx)
}

getCholRobust <- function(matx) {
    .Call('_spatempBFA_getCholRobust', PACKAGE = 'spatempBFA', matx)
}

