# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetRooti <- function(Cov) {
    .Call('_spatTempBFA_GetRooti', PACKAGE = 'spatTempBFA', Cov)
}

getRootiH <- function(Psi, Nu, TempCorInd, seasonPeriod) {
    .Call('_spatTempBFA_getRootiH', PACKAGE = 'spatTempBFA', Psi, Nu, TempCorInd, seasonPeriod)
}

getInvH <- function(Psi, Nu, TempCorInd, seasonPeriod) {
    .Call('_spatTempBFA_getInvH', PACKAGE = 'spatTempBFA', Psi, Nu, TempCorInd, seasonPeriod)
}

getH <- function(Psi, TempCorInd, TimeDist, Nu, seasonPeriod) {
    .Call('_spatTempBFA_getH', PACKAGE = 'spatTempBFA', Psi, TempCorInd, TimeDist, Nu, seasonPeriod)
}

SpEXP <- function(rho, SpDist) {
    .Call('_spatTempBFA_SpEXP', PACKAGE = 'spatTempBFA', rho, SpDist)
}

GetLogLik <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatTempBFA_GetLogLik', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

GetLogLikMean <- function(DatObj_List, Para_List) {
    .Call('_spatTempBFA_GetLogLikMean', PACKAGE = 'spatTempBFA', DatObj_List, Para_List)
}

SamplePPD <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatTempBFA_SamplePPD', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

VAR1bfaRcppFixedL <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, ParaCL_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spatTempBFA_VAR1bfaRcppFixedL', PACKAGE = 'spatTempBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, ParaCL_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

VAR1bfaRcppVaryingLjs <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spatTempBFA_VAR1bfaRcppVaryingLjs', PACKAGE = 'spatTempBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

bfaRcppFixedL <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, ParaCL_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spatTempBFA_bfaRcppFixedL', PACKAGE = 'spatTempBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, ParaCL_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

bfaRcppVaryingLjs <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spatTempBFA_bfaRcppVaryingLjs', PACKAGE = 'spatTempBFA', DatObj_List, HyPara_List, MetrObj_List, Para_List, SpatPara_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

EtaKrigging <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatTempBFA_EtaKrigging', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

VAR1EtaKrigging <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatTempBFA_VAR1EtaKrigging', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

LambdaKrigging <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatTempBFA_LambdaKrigging', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

AlphaKriggingFixedL <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatTempBFA_AlphaKriggingFixedL', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

AlphaKriggingVaryLj <- function(DatObj_List, Para_List, NKeep, Verbose) {
    .Call('_spatTempBFA_AlphaKriggingVaryLj', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, NKeep, Verbose)
}

YKriggingTemp <- function(DatObj_List, Para_List, EtaKrig, NKeep, Verbose) {
    .Call('_spatTempBFA_YKriggingTemp', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, EtaKrig, NKeep, Verbose)
}

VAR1YKriggingTemp <- function(DatObj_List, Para_List, EtaKrig, NKeep, Verbose) {
    .Call('_spatTempBFA_VAR1YKriggingTemp', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, EtaKrig, NKeep, Verbose)
}

YKriggingSpat <- function(DatObj_List, Para_List, LambdaKrig, NKeep, Verbose) {
    .Call('_spatTempBFA_YKriggingSpat', PACKAGE = 'spatTempBFA', DatObj_List, Para_List, LambdaKrig, NKeep, Verbose)
}

UpdateLjVec <- function(U, Weights, K, M, O, LjVec) {
    .Call('_spatTempBFA_UpdateLjVec', PACKAGE = 'spatTempBFA', U, Weights, K, M, O, LjVec)
}

UpdateAlpha <- function(Alpha, K, M, O, LjVec) {
    .Call('_spatTempBFA_UpdateAlpha', PACKAGE = 'spatTempBFA', Alpha, K, M, O, LjVec)
}

GetWeightsVaryLj <- function(Alpha, K, M, O, LjVec) {
    .Call('_spatTempBFA_GetWeightsVaryLj', PACKAGE = 'spatTempBFA', Alpha, K, M, O, LjVec)
}

GetWeightsFixedL <- function(Alpha, K, M, L, O) {
    .Call('_spatTempBFA_GetWeightsFixedL', PACKAGE = 'spatTempBFA', Alpha, K, M, L, O)
}

GetLogWeightsFixedL <- function(Alpha, K, M, L, O) {
    .Call('_spatTempBFA_GetLogWeightsFixedL', PACKAGE = 'spatTempBFA', Alpha, K, M, L, O)
}

CholInv <- function(Cov) {
    .Call('_spatTempBFA_CholInv', PACKAGE = 'spatTempBFA', Cov)
}

whichJsCalc <- function(nnInd) {
    .Call('_spatTempBFA_whichJsCalc', PACKAGE = 'spatTempBFA', nnInd)
}

getCloseNNDmat <- function(matx) {
    .Call('_spatTempBFA_getCloseNNDmat', PACKAGE = 'spatTempBFA', matx)
}

getCholRobust <- function(matx) {
    .Call('_spatTempBFA_getCholRobust', PACKAGE = 'spatTempBFA', matx)
}

